# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d0945a1835f4393ded86372ff3751b794c0acca36fa13b7a2832633a702de5e3e85a06f006536d7f8e455b94475ea267a0b629b8558c0b6166a58ffc88a2091

test:
  secret_key_base: 4ea47b3abe8f416340d6d91d0b29d800cd264d644431ae6c2cc59c71bad7cbf96c9e350c86b6a5ef90268c905de3ff368a1e83606b0bdedad0b92e748cc2822b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
